version: "3"
services:
  triviate-api:
    build: ./backend
    image: ansharyan03/triviate-api:latest
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
  
  web:
    build: ./frontend
    image: ansharyan03/triviate:latest
    ports:
      - 80:80
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY=${SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
      - NEXT_PUBLIC_WEBSOCKET_URL=${WEBSOCKET_URL}